# Configuration for PR auto-labeling (v5 format)

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'
          - 'guidebook/**/*'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile'
          - 'docker-compose*.yml'
          - '.dockerignore'
          - 'docker/**/*'

python:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'
          - 'requirements.txt'

testing:
  - changed-files:
      - any-glob-to-any-file:
          - '**/test_*.py'
          - 'tests/**/*'

ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.json'
          - '**/*.yml'
          - '**/*.yaml'
          - '.env.*'
          - 'env.*'
          - '**/config/**/*'

scripts:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ps1'
          - '**/*.bat'
          - '**/*.sh'
          - 'scripts/**/*'

security:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/security.yml'
          - '**/secrets*'
          - '**/*security*'
