# Configuration for PR auto-labeling
# Labels are automatically applied based on changed files

documentation:
  - any-glob-to-any-file: ['**/*.md', 'docs/**/*', 'guidebook/**/*']

docker:
  - any-glob-to-any-file: ['docker/trading-bridge/Dockerfile', 'docker-compose*.yml', '.dockerignore', 'docker/**/*']

python:
  - any-glob-to-any-file: ['**/*.py', 'docker/trading-bridge/requirements.txt']

testing:
  - any-glob-to-any-file: ['**/test_*.py', 'tests/**/*']

ci-cd:
  - any-glob-to-any-file: ['.github/**/*', '.github/workflows/**/*']

configuration:
  - any-glob-to-any-file: ['**/*.json', '**/*.yml', '**/*.yaml', '.env.*', 'env.*', '**/config/**/*']

scripts:
  - any-glob-to-any-file: ['**/*.ps1', '**/*.bat', '**/*.sh', 'scripts/**/*']

security:
  - any-glob-to-any-file: ['.github/workflows/security.yml', '**/secrets*', '**/*security*']
